[global]
   workgroup = NORTHLINE
   server string = Hold share
   server role = standalone server
   map to guest = Bad User
   guest account = nobody
   smb ports = 445 139
   load printers = no
   printcap name = /dev/null
   disable spoolss = yes
   log file = /dev/null

[public]
   path = /srv/samba/public
   browsable = yes
   guest ok = yes
   read only = yes
   force user = nobody

[print$]
   path = /srv/samba/print
   browsable = yes
   guest ok = yes
   read only = yes
   force user = nobody

[archive]
   path = /srv/samba/archive
   browsable = yes
   guest ok = yes
   read only = yes
   force user = nobody
