listen=YES
listen_ipv6=NO
anonymous_enable=YES
local_enable=NO
write_enable=NO
anon_root=/srv/ftp
no_anon_password=YES
anon_world_readable_only=YES
pasv_enable=YES
pasv_min_port=30000
pasv_max_port=30009
pasv_address=10.23.54.185
seccomp_sandbox=NO
xferlog_enable=NO
vsftpd_log_file=/dev/null
secure_chroot_dir=/var/run/vsftpd/empty
background=YES
