[global]
   workgroup = NORTHLINE
   server string = Dry Dock file yard
   server role = standalone server
   map to guest = Bad User
   guest account = nobody
   smb ports = 445 139
   log file = /dev/null
   logging = syslog@0
   load printers = no
   printcap name = /dev/null
   disable spoolss = yes

[public]
   path = /srv/samba/public
   browsable = yes
   guest ok = yes
   guest only = yes
   read only = yes
   force user = nobody

[scans]
   path = /srv/samba/scans
   browsable = yes
   guest ok = yes
   guest only = yes
   read only = yes
   force user = nobody

[hr-archive]
   path = /srv/samba/hr-archive
   browsable = yes
   guest ok = yes
   guest only = yes
   read only = yes
   force user = nobody
